// Generated by Scripts/generate-functions.py; do not edit.

extension Lungo {

    /// The Lean function type of 1 parameter, as a Swift closure. A Swift closure passed to Lean
    /// may run on any thread; its error is fatal to the Lean program, since Lean's functions
    /// cannot fail. A Lean function returned to Swift fails only with `LungoMalformed`.
    public static func function<A1, R>(_ a1: LungoType<A1>, returns r: LungoType<R>) -> LungoType<(A1) throws -> R> {
        let expr: [UInt8] = [Tag.function] + le32(1) + a1.expr + r.expr
        return LungoType<(A1) throws -> R>(
            expr: expr,
            encode: { w, f in
                try w.hostFunction { input, output in
                    let x1 = try a1.decode(&input)
                    let v: R
                    do {
                        v = try f(x1)
                    } catch {
                        throw LungoHostError("a Swift function passed to Lean failed: \(error)")
                    }
                    try r.encode(&output, v)
                }
            },
            decode: { rd in
                let (program, handle) = try rd.leanFunction()
                return { (x1: A1) throws -> R in
                    try program.callClosure(handle, expr: expr, args: { w in
                        try a1.encode(&w, x1)
                    }, result: r)
                }
            })
    }

    /// The Lean function type of 2 parameters, as a Swift closure. A Swift closure passed to Lean
    /// may run on any thread; its error is fatal to the Lean program, since Lean's functions
    /// cannot fail. A Lean function returned to Swift fails only with `LungoMalformed`.
    public static func function<A1, A2, R>(_ a1: LungoType<A1>, _ a2: LungoType<A2>, returns r: LungoType<R>) -> LungoType<(A1, A2) throws -> R> {
        let expr: [UInt8] = [Tag.function] + le32(2) + a1.expr + a2.expr + r.expr
        return LungoType<(A1, A2) throws -> R>(
            expr: expr,
            encode: { w, f in
                try w.hostFunction { input, output in
                    let x1 = try a1.decode(&input)
                    let x2 = try a2.decode(&input)
                    let v: R
                    do {
                        v = try f(x1, x2)
                    } catch {
                        throw LungoHostError("a Swift function passed to Lean failed: \(error)")
                    }
                    try r.encode(&output, v)
                }
            },
            decode: { rd in
                let (program, handle) = try rd.leanFunction()
                return { (x1: A1, x2: A2) throws -> R in
                    try program.callClosure(handle, expr: expr, args: { w in
                        try a1.encode(&w, x1)
                        try a2.encode(&w, x2)
                    }, result: r)
                }
            })
    }

    /// The Lean function type of 3 parameters, as a Swift closure. A Swift closure passed to Lean
    /// may run on any thread; its error is fatal to the Lean program, since Lean's functions
    /// cannot fail. A Lean function returned to Swift fails only with `LungoMalformed`.
    public static func function<A1, A2, A3, R>(_ a1: LungoType<A1>, _ a2: LungoType<A2>, _ a3: LungoType<A3>, returns r: LungoType<R>) -> LungoType<(A1, A2, A3) throws -> R> {
        let expr: [UInt8] = [Tag.function] + le32(3) + a1.expr + a2.expr + a3.expr + r.expr
        return LungoType<(A1, A2, A3) throws -> R>(
            expr: expr,
            encode: { w, f in
                try w.hostFunction { input, output in
                    let x1 = try a1.decode(&input)
                    let x2 = try a2.decode(&input)
                    let x3 = try a3.decode(&input)
                    let v: R
                    do {
                        v = try f(x1, x2, x3)
                    } catch {
                        throw LungoHostError("a Swift function passed to Lean failed: \(error)")
                    }
                    try r.encode(&output, v)
                }
            },
            decode: { rd in
                let (program, handle) = try rd.leanFunction()
                return { (x1: A1, x2: A2, x3: A3) throws -> R in
                    try program.callClosure(handle, expr: expr, args: { w in
                        try a1.encode(&w, x1)
                        try a2.encode(&w, x2)
                        try a3.encode(&w, x3)
                    }, result: r)
                }
            })
    }

    /// The Lean function type of 4 parameters, as a Swift closure. A Swift closure passed to Lean
    /// may run on any thread; its error is fatal to the Lean program, since Lean's functions
    /// cannot fail. A Lean function returned to Swift fails only with `LungoMalformed`.
    public static func function<A1, A2, A3, A4, R>(_ a1: LungoType<A1>, _ a2: LungoType<A2>, _ a3: LungoType<A3>, _ a4: LungoType<A4>, returns r: LungoType<R>) -> LungoType<(A1, A2, A3, A4) throws -> R> {
        let expr: [UInt8] = [Tag.function] + le32(4) + a1.expr + a2.expr + a3.expr + a4.expr + r.expr
        return LungoType<(A1, A2, A3, A4) throws -> R>(
            expr: expr,
            encode: { w, f in
                try w.hostFunction { input, output in
                    let x1 = try a1.decode(&input)
                    let x2 = try a2.decode(&input)
                    let x3 = try a3.decode(&input)
                    let x4 = try a4.decode(&input)
                    let v: R
                    do {
                        v = try f(x1, x2, x3, x4)
                    } catch {
                        throw LungoHostError("a Swift function passed to Lean failed: \(error)")
                    }
                    try r.encode(&output, v)
                }
            },
            decode: { rd in
                let (program, handle) = try rd.leanFunction()
                return { (x1: A1, x2: A2, x3: A3, x4: A4) throws -> R in
                    try program.callClosure(handle, expr: expr, args: { w in
                        try a1.encode(&w, x1)
                        try a2.encode(&w, x2)
                        try a3.encode(&w, x3)
                        try a4.encode(&w, x4)
                    }, result: r)
                }
            })
    }

    /// The Lean function type of 5 parameters, as a Swift closure. A Swift closure passed to Lean
    /// may run on any thread; its error is fatal to the Lean program, since Lean's functions
    /// cannot fail. A Lean function returned to Swift fails only with `LungoMalformed`.
    public static func function<A1, A2, A3, A4, A5, R>(_ a1: LungoType<A1>, _ a2: LungoType<A2>, _ a3: LungoType<A3>, _ a4: LungoType<A4>, _ a5: LungoType<A5>, returns r: LungoType<R>) -> LungoType<(A1, A2, A3, A4, A5) throws -> R> {
        let expr: [UInt8] = [Tag.function] + le32(5) + a1.expr + a2.expr + a3.expr + a4.expr + a5.expr + r.expr
        return LungoType<(A1, A2, A3, A4, A5) throws -> R>(
            expr: expr,
            encode: { w, f in
                try w.hostFunction { input, output in
                    let x1 = try a1.decode(&input)
                    let x2 = try a2.decode(&input)
                    let x3 = try a3.decode(&input)
                    let x4 = try a4.decode(&input)
                    let x5 = try a5.decode(&input)
                    let v: R
                    do {
                        v = try f(x1, x2, x3, x4, x5)
                    } catch {
                        throw LungoHostError("a Swift function passed to Lean failed: \(error)")
                    }
                    try r.encode(&output, v)
                }
            },
            decode: { rd in
                let (program, handle) = try rd.leanFunction()
                return { (x1: A1, x2: A2, x3: A3, x4: A4, x5: A5) throws -> R in
                    try program.callClosure(handle, expr: expr, args: { w in
                        try a1.encode(&w, x1)
                        try a2.encode(&w, x2)
                        try a3.encode(&w, x3)
                        try a4.encode(&w, x4)
                        try a5.encode(&w, x5)
                    }, result: r)
                }
            })
    }

    /// The Lean function type of 6 parameters, as a Swift closure. A Swift closure passed to Lean
    /// may run on any thread; its error is fatal to the Lean program, since Lean's functions
    /// cannot fail. A Lean function returned to Swift fails only with `LungoMalformed`.
    public static func function<A1, A2, A3, A4, A5, A6, R>(_ a1: LungoType<A1>, _ a2: LungoType<A2>, _ a3: LungoType<A3>, _ a4: LungoType<A4>, _ a5: LungoType<A5>, _ a6: LungoType<A6>, returns r: LungoType<R>) -> LungoType<(A1, A2, A3, A4, A5, A6) throws -> R> {
        let expr: [UInt8] = [Tag.function] + le32(6) + a1.expr + a2.expr + a3.expr + a4.expr + a5.expr + a6.expr + r.expr
        return LungoType<(A1, A2, A3, A4, A5, A6) throws -> R>(
            expr: expr,
            encode: { w, f in
                try w.hostFunction { input, output in
                    let x1 = try a1.decode(&input)
                    let x2 = try a2.decode(&input)
                    let x3 = try a3.decode(&input)
                    let x4 = try a4.decode(&input)
                    let x5 = try a5.decode(&input)
                    let x6 = try a6.decode(&input)
                    let v: R
                    do {
                        v = try f(x1, x2, x3, x4, x5, x6)
                    } catch {
                        throw LungoHostError("a Swift function passed to Lean failed: \(error)")
                    }
                    try r.encode(&output, v)
                }
            },
            decode: { rd in
                let (program, handle) = try rd.leanFunction()
                return { (x1: A1, x2: A2, x3: A3, x4: A4, x5: A5, x6: A6) throws -> R in
                    try program.callClosure(handle, expr: expr, args: { w in
                        try a1.encode(&w, x1)
                        try a2.encode(&w, x2)
                        try a3.encode(&w, x3)
                        try a4.encode(&w, x4)
                        try a5.encode(&w, x5)
                        try a6.encode(&w, x6)
                    }, result: r)
                }
            })
    }

    /// The Lean function type of 7 parameters, as a Swift closure. A Swift closure passed to Lean
    /// may run on any thread; its error is fatal to the Lean program, since Lean's functions
    /// cannot fail. A Lean function returned to Swift fails only with `LungoMalformed`.
    public static func function<A1, A2, A3, A4, A5, A6, A7, R>(_ a1: LungoType<A1>, _ a2: LungoType<A2>, _ a3: LungoType<A3>, _ a4: LungoType<A4>, _ a5: LungoType<A5>, _ a6: LungoType<A6>, _ a7: LungoType<A7>, returns r: LungoType<R>) -> LungoType<(A1, A2, A3, A4, A5, A6, A7) throws -> R> {
        let expr: [UInt8] = [Tag.function] + le32(7) + a1.expr + a2.expr + a3.expr + a4.expr + a5.expr + a6.expr + a7.expr + r.expr
        return LungoType<(A1, A2, A3, A4, A5, A6, A7) throws -> R>(
            expr: expr,
            encode: { w, f in
                try w.hostFunction { input, output in
                    let x1 = try a1.decode(&input)
                    let x2 = try a2.decode(&input)
                    let x3 = try a3.decode(&input)
                    let x4 = try a4.decode(&input)
                    let x5 = try a5.decode(&input)
                    let x6 = try a6.decode(&input)
                    let x7 = try a7.decode(&input)
                    let v: R
                    do {
                        v = try f(x1, x2, x3, x4, x5, x6, x7)
                    } catch {
                        throw LungoHostError("a Swift function passed to Lean failed: \(error)")
                    }
                    try r.encode(&output, v)
                }
            },
            decode: { rd in
                let (program, handle) = try rd.leanFunction()
                return { (x1: A1, x2: A2, x3: A3, x4: A4, x5: A5, x6: A6, x7: A7) throws -> R in
                    try program.callClosure(handle, expr: expr, args: { w in
                        try a1.encode(&w, x1)
                        try a2.encode(&w, x2)
                        try a3.encode(&w, x3)
                        try a4.encode(&w, x4)
                        try a5.encode(&w, x5)
                        try a6.encode(&w, x6)
                        try a7.encode(&w, x7)
                    }, result: r)
                }
            })
    }

    /// The Lean function type of 8 parameters, as a Swift closure. A Swift closure passed to Lean
    /// may run on any thread; its error is fatal to the Lean program, since Lean's functions
    /// cannot fail. A Lean function returned to Swift fails only with `LungoMalformed`.
    public static func function<A1, A2, A3, A4, A5, A6, A7, A8, R>(_ a1: LungoType<A1>, _ a2: LungoType<A2>, _ a3: LungoType<A3>, _ a4: LungoType<A4>, _ a5: LungoType<A5>, _ a6: LungoType<A6>, _ a7: LungoType<A7>, _ a8: LungoType<A8>, returns r: LungoType<R>) -> LungoType<(A1, A2, A3, A4, A5, A6, A7, A8) throws -> R> {
        let expr: [UInt8] = [Tag.function] + le32(8) + a1.expr + a2.expr + a3.expr + a4.expr + a5.expr + a6.expr + a7.expr + a8.expr + r.expr
        return LungoType<(A1, A2, A3, A4, A5, A6, A7, A8) throws -> R>(
            expr: expr,
            encode: { w, f in
                try w.hostFunction { input, output in
                    let x1 = try a1.decode(&input)
                    let x2 = try a2.decode(&input)
                    let x3 = try a3.decode(&input)
                    let x4 = try a4.decode(&input)
                    let x5 = try a5.decode(&input)
                    let x6 = try a6.decode(&input)
                    let x7 = try a7.decode(&input)
                    let x8 = try a8.decode(&input)
                    let v: R
                    do {
                        v = try f(x1, x2, x3, x4, x5, x6, x7, x8)
                    } catch {
                        throw LungoHostError("a Swift function passed to Lean failed: \(error)")
                    }
                    try r.encode(&output, v)
                }
            },
            decode: { rd in
                let (program, handle) = try rd.leanFunction()
                return { (x1: A1, x2: A2, x3: A3, x4: A4, x5: A5, x6: A6, x7: A7, x8: A8) throws -> R in
                    try program.callClosure(handle, expr: expr, args: { w in
                        try a1.encode(&w, x1)
                        try a2.encode(&w, x2)
                        try a3.encode(&w, x3)
                        try a4.encode(&w, x4)
                        try a5.encode(&w, x5)
                        try a6.encode(&w, x6)
                        try a7.encode(&w, x7)
                        try a8.encode(&w, x8)
                    }, result: r)
                }
            })
    }

    /// The Lean function type of 9 parameters, as a Swift closure. A Swift closure passed to Lean
    /// may run on any thread; its error is fatal to the Lean program, since Lean's functions
    /// cannot fail. A Lean function returned to Swift fails only with `LungoMalformed`.
    public static func function<A1, A2, A3, A4, A5, A6, A7, A8, A9, R>(_ a1: LungoType<A1>, _ a2: LungoType<A2>, _ a3: LungoType<A3>, _ a4: LungoType<A4>, _ a5: LungoType<A5>, _ a6: LungoType<A6>, _ a7: LungoType<A7>, _ a8: LungoType<A8>, _ a9: LungoType<A9>, returns r: LungoType<R>) -> LungoType<(A1, A2, A3, A4, A5, A6, A7, A8, A9) throws -> R> {
        let expr: [UInt8] = [Tag.function] + le32(9) + a1.expr + a2.expr + a3.expr + a4.expr + a5.expr + a6.expr + a7.expr + a8.expr + a9.expr + r.expr
        return LungoType<(A1, A2, A3, A4, A5, A6, A7, A8, A9) throws -> R>(
            expr: expr,
            encode: { w, f in
                try w.hostFunction { input, output in
                    let x1 = try a1.decode(&input)
                    let x2 = try a2.decode(&input)
                    let x3 = try a3.decode(&input)
                    let x4 = try a4.decode(&input)
                    let x5 = try a5.decode(&input)
                    let x6 = try a6.decode(&input)
                    let x7 = try a7.decode(&input)
                    let x8 = try a8.decode(&input)
                    let x9 = try a9.decode(&input)
                    let v: R
                    do {
                        v = try f(x1, x2, x3, x4, x5, x6, x7, x8, x9)
                    } catch {
                        throw LungoHostError("a Swift function passed to Lean failed: \(error)")
                    }
                    try r.encode(&output, v)
                }
            },
            decode: { rd in
                let (program, handle) = try rd.leanFunction()
                return { (x1: A1, x2: A2, x3: A3, x4: A4, x5: A5, x6: A6, x7: A7, x8: A8, x9: A9) throws -> R in
                    try program.callClosure(handle, expr: expr, args: { w in
                        try a1.encode(&w, x1)
                        try a2.encode(&w, x2)
                        try a3.encode(&w, x3)
                        try a4.encode(&w, x4)
                        try a5.encode(&w, x5)
                        try a6.encode(&w, x6)
                        try a7.encode(&w, x7)
                        try a8.encode(&w, x8)
                        try a9.encode(&w, x9)
                    }, result: r)
                }
            })
    }

    /// The Lean function type of 10 parameters, as a Swift closure. A Swift closure passed to Lean
    /// may run on any thread; its error is fatal to the Lean program, since Lean's functions
    /// cannot fail. A Lean function returned to Swift fails only with `LungoMalformed`.
    public static func function<A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, R>(_ a1: LungoType<A1>, _ a2: LungoType<A2>, _ a3: LungoType<A3>, _ a4: LungoType<A4>, _ a5: LungoType<A5>, _ a6: LungoType<A6>, _ a7: LungoType<A7>, _ a8: LungoType<A8>, _ a9: LungoType<A9>, _ a10: LungoType<A10>, returns r: LungoType<R>) -> LungoType<(A1, A2, A3, A4, A5, A6, A7, A8, A9, A10) throws -> R> {
        let expr: [UInt8] = [Tag.function] + le32(10) + a1.expr + a2.expr + a3.expr + a4.expr + a5.expr + a6.expr + a7.expr + a8.expr + a9.expr + a10.expr + r.expr
        return LungoType<(A1, A2, A3, A4, A5, A6, A7, A8, A9, A10) throws -> R>(
            expr: expr,
            encode: { w, f in
                try w.hostFunction { input, output in
                    let x1 = try a1.decode(&input)
                    let x2 = try a2.decode(&input)
                    let x3 = try a3.decode(&input)
                    let x4 = try a4.decode(&input)
                    let x5 = try a5.decode(&input)
                    let x6 = try a6.decode(&input)
                    let x7 = try a7.decode(&input)
                    let x8 = try a8.decode(&input)
                    let x9 = try a9.decode(&input)
                    let x10 = try a10.decode(&input)
                    let v: R
                    do {
                        v = try f(x1, x2, x3, x4, x5, x6, x7, x8, x9, x10)
                    } catch {
                        throw LungoHostError("a Swift function passed to Lean failed: \(error)")
                    }
                    try r.encode(&output, v)
                }
            },
            decode: { rd in
                let (program, handle) = try rd.leanFunction()
                return { (x1: A1, x2: A2, x3: A3, x4: A4, x5: A5, x6: A6, x7: A7, x8: A8, x9: A9, x10: A10) throws -> R in
                    try program.callClosure(handle, expr: expr, args: { w in
                        try a1.encode(&w, x1)
                        try a2.encode(&w, x2)
                        try a3.encode(&w, x3)
                        try a4.encode(&w, x4)
                        try a5.encode(&w, x5)
                        try a6.encode(&w, x6)
                        try a7.encode(&w, x7)
                        try a8.encode(&w, x8)
                        try a9.encode(&w, x9)
                        try a10.encode(&w, x10)
                    }, result: r)
                }
            })
    }

    /// The Lean function type of 11 parameters, as a Swift closure. A Swift closure passed to Lean
    /// may run on any thread; its error is fatal to the Lean program, since Lean's functions
    /// cannot fail. A Lean function returned to Swift fails only with `LungoMalformed`.
    public static func function<A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, A11, R>(_ a1: LungoType<A1>, _ a2: LungoType<A2>, _ a3: LungoType<A3>, _ a4: LungoType<A4>, _ a5: LungoType<A5>, _ a6: LungoType<A6>, _ a7: LungoType<A7>, _ a8: LungoType<A8>, _ a9: LungoType<A9>, _ a10: LungoType<A10>, _ a11: LungoType<A11>, returns r: LungoType<R>) -> LungoType<(A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, A11) throws -> R> {
        let expr: [UInt8] = [Tag.function] + le32(11) + a1.expr + a2.expr + a3.expr + a4.expr + a5.expr + a6.expr + a7.expr + a8.expr + a9.expr + a10.expr + a11.expr + r.expr
        return LungoType<(A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, A11) throws -> R>(
            expr: expr,
            encode: { w, f in
                try w.hostFunction { input, output in
                    let x1 = try a1.decode(&input)
                    let x2 = try a2.decode(&input)
                    let x3 = try a3.decode(&input)
                    let x4 = try a4.decode(&input)
                    let x5 = try a5.decode(&input)
                    let x6 = try a6.decode(&input)
                    let x7 = try a7.decode(&input)
                    let x8 = try a8.decode(&input)
                    let x9 = try a9.decode(&input)
                    let x10 = try a10.decode(&input)
                    let x11 = try a11.decode(&input)
                    let v: R
                    do {
                        v = try f(x1, x2, x3, x4, x5, x6, x7, x8, x9, x10, x11)
                    } catch {
                        throw LungoHostError("a Swift function passed to Lean failed: \(error)")
                    }
                    try r.encode(&output, v)
                }
            },
            decode: { rd in
                let (program, handle) = try rd.leanFunction()
                return { (x1: A1, x2: A2, x3: A3, x4: A4, x5: A5, x6: A6, x7: A7, x8: A8, x9: A9, x10: A10, x11: A11) throws -> R in
                    try program.callClosure(handle, expr: expr, args: { w in
                        try a1.encode(&w, x1)
                        try a2.encode(&w, x2)
                        try a3.encode(&w, x3)
                        try a4.encode(&w, x4)
                        try a5.encode(&w, x5)
                        try a6.encode(&w, x6)
                        try a7.encode(&w, x7)
                        try a8.encode(&w, x8)
                        try a9.encode(&w, x9)
                        try a10.encode(&w, x10)
                        try a11.encode(&w, x11)
                    }, result: r)
                }
            })
    }

    /// The Lean function type of 12 parameters, as a Swift closure. A Swift closure passed to Lean
    /// may run on any thread; its error is fatal to the Lean program, since Lean's functions
    /// cannot fail. A Lean function returned to Swift fails only with `LungoMalformed`.
    public static func function<A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, A11, A12, R>(_ a1: LungoType<A1>, _ a2: LungoType<A2>, _ a3: LungoType<A3>, _ a4: LungoType<A4>, _ a5: LungoType<A5>, _ a6: LungoType<A6>, _ a7: LungoType<A7>, _ a8: LungoType<A8>, _ a9: LungoType<A9>, _ a10: LungoType<A10>, _ a11: LungoType<A11>, _ a12: LungoType<A12>, returns r: LungoType<R>) -> LungoType<(A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, A11, A12) throws -> R> {
        let expr: [UInt8] = [Tag.function] + le32(12) + a1.expr + a2.expr + a3.expr + a4.expr + a5.expr + a6.expr + a7.expr + a8.expr + a9.expr + a10.expr + a11.expr + a12.expr + r.expr
        return LungoType<(A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, A11, A12) throws -> R>(
            expr: expr,
            encode: { w, f in
                try w.hostFunction { input, output in
                    let x1 = try a1.decode(&input)
                    let x2 = try a2.decode(&input)
                    let x3 = try a3.decode(&input)
                    let x4 = try a4.decode(&input)
                    let x5 = try a5.decode(&input)
                    let x6 = try a6.decode(&input)
                    let x7 = try a7.decode(&input)
                    let x8 = try a8.decode(&input)
                    let x9 = try a9.decode(&input)
                    let x10 = try a10.decode(&input)
                    let x11 = try a11.decode(&input)
                    let x12 = try a12.decode(&input)
                    let v: R
                    do {
                        v = try f(x1, x2, x3, x4, x5, x6, x7, x8, x9, x10, x11, x12)
                    } catch {
                        throw LungoHostError("a Swift function passed to Lean failed: \(error)")
                    }
                    try r.encode(&output, v)
                }
            },
            decode: { rd in
                let (program, handle) = try rd.leanFunction()
                return { (x1: A1, x2: A2, x3: A3, x4: A4, x5: A5, x6: A6, x7: A7, x8: A8, x9: A9, x10: A10, x11: A11, x12: A12) throws -> R in
                    try program.callClosure(handle, expr: expr, args: { w in
                        try a1.encode(&w, x1)
                        try a2.encode(&w, x2)
                        try a3.encode(&w, x3)
                        try a4.encode(&w, x4)
                        try a5.encode(&w, x5)
                        try a6.encode(&w, x6)
                        try a7.encode(&w, x7)
                        try a8.encode(&w, x8)
                        try a9.encode(&w, x9)
                        try a10.encode(&w, x10)
                        try a11.encode(&w, x11)
                        try a12.encode(&w, x12)
                    }, result: r)
                }
            })
    }

    /// The Lean function type of 13 parameters, as a Swift closure. A Swift closure passed to Lean
    /// may run on any thread; its error is fatal to the Lean program, since Lean's functions
    /// cannot fail. A Lean function returned to Swift fails only with `LungoMalformed`.
    public static func function<A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, A11, A12, A13, R>(_ a1: LungoType<A1>, _ a2: LungoType<A2>, _ a3: LungoType<A3>, _ a4: LungoType<A4>, _ a5: LungoType<A5>, _ a6: LungoType<A6>, _ a7: LungoType<A7>, _ a8: LungoType<A8>, _ a9: LungoType<A9>, _ a10: LungoType<A10>, _ a11: LungoType<A11>, _ a12: LungoType<A12>, _ a13: LungoType<A13>, returns r: LungoType<R>) -> LungoType<(A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, A11, A12, A13) throws -> R> {
        let expr: [UInt8] = [Tag.function] + le32(13) + a1.expr + a2.expr + a3.expr + a4.expr + a5.expr + a6.expr + a7.expr + a8.expr + a9.expr + a10.expr + a11.expr + a12.expr + a13.expr + r.expr
        return LungoType<(A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, A11, A12, A13) throws -> R>(
            expr: expr,
            encode: { w, f in
                try w.hostFunction { input, output in
                    let x1 = try a1.decode(&input)
                    let x2 = try a2.decode(&input)
                    let x3 = try a3.decode(&input)
                    let x4 = try a4.decode(&input)
                    let x5 = try a5.decode(&input)
                    let x6 = try a6.decode(&input)
                    let x7 = try a7.decode(&input)
                    let x8 = try a8.decode(&input)
                    let x9 = try a9.decode(&input)
                    let x10 = try a10.decode(&input)
                    let x11 = try a11.decode(&input)
                    let x12 = try a12.decode(&input)
                    let x13 = try a13.decode(&input)
                    let v: R
                    do {
                        v = try f(x1, x2, x3, x4, x5, x6, x7, x8, x9, x10, x11, x12, x13)
                    } catch {
                        throw LungoHostError("a Swift function passed to Lean failed: \(error)")
                    }
                    try r.encode(&output, v)
                }
            },
            decode: { rd in
                let (program, handle) = try rd.leanFunction()
                return { (x1: A1, x2: A2, x3: A3, x4: A4, x5: A5, x6: A6, x7: A7, x8: A8, x9: A9, x10: A10, x11: A11, x12: A12, x13: A13) throws -> R in
                    try program.callClosure(handle, expr: expr, args: { w in
                        try a1.encode(&w, x1)
                        try a2.encode(&w, x2)
                        try a3.encode(&w, x3)
                        try a4.encode(&w, x4)
                        try a5.encode(&w, x5)
                        try a6.encode(&w, x6)
                        try a7.encode(&w, x7)
                        try a8.encode(&w, x8)
                        try a9.encode(&w, x9)
                        try a10.encode(&w, x10)
                        try a11.encode(&w, x11)
                        try a12.encode(&w, x12)
                        try a13.encode(&w, x13)
                    }, result: r)
                }
            })
    }

    /// The Lean function type of 14 parameters, as a Swift closure. A Swift closure passed to Lean
    /// may run on any thread; its error is fatal to the Lean program, since Lean's functions
    /// cannot fail. A Lean function returned to Swift fails only with `LungoMalformed`.
    public static func function<A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, A11, A12, A13, A14, R>(_ a1: LungoType<A1>, _ a2: LungoType<A2>, _ a3: LungoType<A3>, _ a4: LungoType<A4>, _ a5: LungoType<A5>, _ a6: LungoType<A6>, _ a7: LungoType<A7>, _ a8: LungoType<A8>, _ a9: LungoType<A9>, _ a10: LungoType<A10>, _ a11: LungoType<A11>, _ a12: LungoType<A12>, _ a13: LungoType<A13>, _ a14: LungoType<A14>, returns r: LungoType<R>) -> LungoType<(A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, A11, A12, A13, A14) throws -> R> {
        let expr: [UInt8] = [Tag.function] + le32(14) + a1.expr + a2.expr + a3.expr + a4.expr + a5.expr + a6.expr + a7.expr + a8.expr + a9.expr + a10.expr + a11.expr + a12.expr + a13.expr + a14.expr + r.expr
        return LungoType<(A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, A11, A12, A13, A14) throws -> R>(
            expr: expr,
            encode: { w, f in
                try w.hostFunction { input, output in
                    let x1 = try a1.decode(&input)
                    let x2 = try a2.decode(&input)
                    let x3 = try a3.decode(&input)
                    let x4 = try a4.decode(&input)
                    let x5 = try a5.decode(&input)
                    let x6 = try a6.decode(&input)
                    let x7 = try a7.decode(&input)
                    let x8 = try a8.decode(&input)
                    let x9 = try a9.decode(&input)
                    let x10 = try a10.decode(&input)
                    let x11 = try a11.decode(&input)
                    let x12 = try a12.decode(&input)
                    let x13 = try a13.decode(&input)
                    let x14 = try a14.decode(&input)
                    let v: R
                    do {
                        v = try f(x1, x2, x3, x4, x5, x6, x7, x8, x9, x10, x11, x12, x13, x14)
                    } catch {
                        throw LungoHostError("a Swift function passed to Lean failed: \(error)")
                    }
                    try r.encode(&output, v)
                }
            },
            decode: { rd in
                let (program, handle) = try rd.leanFunction()
                return { (x1: A1, x2: A2, x3: A3, x4: A4, x5: A5, x6: A6, x7: A7, x8: A8, x9: A9, x10: A10, x11: A11, x12: A12, x13: A13, x14: A14) throws -> R in
                    try program.callClosure(handle, expr: expr, args: { w in
                        try a1.encode(&w, x1)
                        try a2.encode(&w, x2)
                        try a3.encode(&w, x3)
                        try a4.encode(&w, x4)
                        try a5.encode(&w, x5)
                        try a6.encode(&w, x6)
                        try a7.encode(&w, x7)
                        try a8.encode(&w, x8)
                        try a9.encode(&w, x9)
                        try a10.encode(&w, x10)
                        try a11.encode(&w, x11)
                        try a12.encode(&w, x12)
                        try a13.encode(&w, x13)
                        try a14.encode(&w, x14)
                    }, result: r)
                }
            })
    }

    /// The Lean function type of 15 parameters, as a Swift closure. A Swift closure passed to Lean
    /// may run on any thread; its error is fatal to the Lean program, since Lean's functions
    /// cannot fail. A Lean function returned to Swift fails only with `LungoMalformed`.
    public static func function<A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, A11, A12, A13, A14, A15, R>(_ a1: LungoType<A1>, _ a2: LungoType<A2>, _ a3: LungoType<A3>, _ a4: LungoType<A4>, _ a5: LungoType<A5>, _ a6: LungoType<A6>, _ a7: LungoType<A7>, _ a8: LungoType<A8>, _ a9: LungoType<A9>, _ a10: LungoType<A10>, _ a11: LungoType<A11>, _ a12: LungoType<A12>, _ a13: LungoType<A13>, _ a14: LungoType<A14>, _ a15: LungoType<A15>, returns r: LungoType<R>) -> LungoType<(A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, A11, A12, A13, A14, A15) throws -> R> {
        let expr: [UInt8] = [Tag.function] + le32(15) + a1.expr + a2.expr + a3.expr + a4.expr + a5.expr + a6.expr + a7.expr + a8.expr + a9.expr + a10.expr + a11.expr + a12.expr + a13.expr + a14.expr + a15.expr + r.expr
        return LungoType<(A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, A11, A12, A13, A14, A15) throws -> R>(
            expr: expr,
            encode: { w, f in
                try w.hostFunction { input, output in
                    let x1 = try a1.decode(&input)
                    let x2 = try a2.decode(&input)
                    let x3 = try a3.decode(&input)
                    let x4 = try a4.decode(&input)
                    let x5 = try a5.decode(&input)
                    let x6 = try a6.decode(&input)
                    let x7 = try a7.decode(&input)
                    let x8 = try a8.decode(&input)
                    let x9 = try a9.decode(&input)
                    let x10 = try a10.decode(&input)
                    let x11 = try a11.decode(&input)
                    let x12 = try a12.decode(&input)
                    let x13 = try a13.decode(&input)
                    let x14 = try a14.decode(&input)
                    let x15 = try a15.decode(&input)
                    let v: R
                    do {
                        v = try f(x1, x2, x3, x4, x5, x6, x7, x8, x9, x10, x11, x12, x13, x14, x15)
                    } catch {
                        throw LungoHostError("a Swift function passed to Lean failed: \(error)")
                    }
                    try r.encode(&output, v)
                }
            },
            decode: { rd in
                let (program, handle) = try rd.leanFunction()
                return { (x1: A1, x2: A2, x3: A3, x4: A4, x5: A5, x6: A6, x7: A7, x8: A8, x9: A9, x10: A10, x11: A11, x12: A12, x13: A13, x14: A14, x15: A15) throws -> R in
                    try program.callClosure(handle, expr: expr, args: { w in
                        try a1.encode(&w, x1)
                        try a2.encode(&w, x2)
                        try a3.encode(&w, x3)
                        try a4.encode(&w, x4)
                        try a5.encode(&w, x5)
                        try a6.encode(&w, x6)
                        try a7.encode(&w, x7)
                        try a8.encode(&w, x8)
                        try a9.encode(&w, x9)
                        try a10.encode(&w, x10)
                        try a11.encode(&w, x11)
                        try a12.encode(&w, x12)
                        try a13.encode(&w, x13)
                        try a14.encode(&w, x14)
                        try a15.encode(&w, x15)
                    }, result: r)
                }
            })
    }
}
