#!/usr/bin/env python3
"""Writes Sources/LungoKit/Functions.swift: the descriptors of Lean function types of 1 to 15
parameters (the wire format's limit) as Swift closures."""

import os

out = [
    "// Generated by Scripts/generate-functions.py; do not edit.",
    "",
    "extension Lungo {",
]
for n in range(1, 16):
    ps = [f"A{i}" for i in range(1, n + 1)]
    generics = ", ".join(ps + ["R"])
    fn = f"({', '.join(ps)}) throws -> R"
    params = ", ".join(f"_ a{i}: LungoType<A{i}>" for i in range(1, n + 1))
    expr = " + ".join(f"a{i}.expr" for i in range(1, n + 1))
    decodes = "\n".join(f"                    let x{i} = try a{i}.decode(&input)" for i in range(1, n + 1))
    args = ", ".join(f"x{i}" for i in range(1, n + 1))
    sig = ", ".join(f"x{i}: A{i}" for i in range(1, n + 1))
    encodes = "\n".join(f"                        try a{i}.encode(&w, x{i})" for i in range(1, n + 1))
    out.append(f"""
    /// The Lean function type of {n} parameter{'s' if n > 1 else ''}, as a Swift closure. A Swift closure passed to Lean
    /// may run on any thread; its error is fatal to the Lean program, since Lean's functions
    /// cannot fail. A Lean function returned to Swift fails only with `LungoMalformed`.
    public static func function<{generics}>({params}, returns r: LungoType<R>) -> LungoType<{fn}> {{
        let expr: [UInt8] = [Tag.function] + le32({n}) + {expr} + r.expr
        return LungoType<{fn}>(
            expr: expr,
            encode: {{ w, f in
                try w.hostFunction {{ input, output in
{decodes}
                    let v: R
                    do {{
                        v = try f({args})
                    }} catch {{
                        throw LungoHostError("a Swift function passed to Lean failed: \\(error)")
                    }}
                    try r.encode(&output, v)
                }}
            }},
            decode: {{ rd in
                let (program, handle) = try rd.leanFunction()
                return {{ ({sig}) throws -> R in
                    try program.callClosure(handle, expr: expr, args: {{ w in
{encodes}
                    }}, result: r)
                }}
            }})
    }}""")
out.append("}")
out.append("")
path = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "Sources", "LungoKit", "Functions.swift")
with open(path, "w", encoding="utf-8") as f:
    f.write("\n".join(out))
